common: &common
  adapter: mysql2
  host: "localhost"
  port: 3306
#  socket: /tmp/mysql.sock
  username: "utopiaspora"
  password: "utopiaspora"
  charset: utf8
  collation: utf8_bin


development:
  <<: *common
  database: utopiaspora_development

production:
  <<: *common
  database: utopiaspora_production

test:
  <<: *common
  database: utopiaspora_test


